CIRCUITPY_WIFI_SSID = "<<wifi ssid>>"
CIRCUITPY_WIFI_PASSWORD = "<<wifi password>>"
CIRCUITPY_WEB_API_PASSWORD = "passw0rd"
CIRCUITPY_WEB_API_PORT = 80

SOFTWARE_TYPE = "DEVIOLINK_BOARD"
SOFTWARE_VERSION = "0.0.1"